export const ERC20_ABI = [
	{
		constant: true,
		inputs: [{ name: '_owner', type: 'address' }],
		name: 'balanceOf',
		outputs: [{ name: 'balance', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'decimals',
		outputs: [{ name: '', type: 'uint8' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'symbol',
		outputs: [{ name: '', type: 'string' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'name',
		outputs: [{ name: '', type: 'string' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'totalSupply',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [
			{ name: '_spender', type: 'address' },
			{ name: '_value', type: 'uint256' },
		],
		name: 'approve',
		outputs: [{ name: '', type: 'bool' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [
			{ name: '_to', type: 'address' },
			{ name: '_value', type: 'uint256' },
		],
		name: 'transfer',
		outputs: [{ name: '', type: 'bool' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [
			{ name: '_from', type: 'address' },
			{ name: '_to', type: 'address' },
			{ name: '_value', type: 'uint256' },
		],
		name: 'transferFrom',
		outputs: [{ name: '', type: 'bool' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [
			{ name: '_owner', type: 'address' },
			{ name: '_spender', type: 'address' },
		],
		name: 'allowance',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, name: 'from', type: 'address' },
			{ indexed: true, name: 'to', type: 'address' },
			{ indexed: false, name: 'value', type: 'uint256' },
		],
		name: 'Transfer',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, name: 'owner', type: 'address' },
			{ indexed: true, name: 'spender', type: 'address' },
			{ indexed: false, name: 'value', type: 'uint256' },
		],
		name: 'Approval',
		type: 'event',
	},
]

export const CTOKEN_ABI = [
	{
		constant: false,
		inputs: [{ name: 'mintAmount', type: 'uint256' }],
		name: 'mint',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [{ name: 'redeemTokens', type: 'uint256' }],
		name: 'redeem',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [{ name: 'redeemAmount', type: 'uint256' }],
		name: 'redeemUnderlying',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [{ name: 'borrowAmount', type: 'uint256' }],
		name: 'borrow',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [{ name: 'repayAmount', type: 'uint256' }],
		name: 'repayBorrow',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [
			{ name: 'borrower', type: 'address' },
			{ name: 'repayAmount', type: 'uint256' },
		],
		name: 'repayBorrowBehalf',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [
			{ name: 'borrower', type: 'address' },
			{ name: 'repayAmount', type: 'uint256' },
			{ name: 'cTokenCollateral', type: 'address' },
		],
		name: 'liquidateBorrow',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [{ name: 'owner', type: 'address' }],
		name: 'balanceOf',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [{ name: 'account', type: 'address' }],
		name: 'borrowBalanceCurrent',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [{ name: 'account', type: 'address' }],
		name: 'borrowBalanceStored',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'exchangeRateStored',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [],
		name: 'exchangeRateCurrent',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'supplyRatePerBlock',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'borrowRatePerBlock',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'totalSupply',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'totalBorrows',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'totalReserves',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'reserveFactorMantissa',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'getCash',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [],
		name: 'accrueInterest',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [
			{ name: 'dst', type: 'address' },
			{ name: 'amount', type: 'uint256' },
		],
		name: 'transfer',
		outputs: [{ name: '', type: 'bool' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [
			{ name: 'src', type: 'address' },
			{ name: 'dst', type: 'address' },
			{ name: 'amount', type: 'uint256' },
		],
		name: 'transferFrom',
		outputs: [{ name: '', type: 'bool' }],
		type: 'function',
	},
	{
		constant: false,
		inputs: [
			{ name: 'spender', type: 'address' },
			{ name: 'amount', type: 'uint256' },
		],
		name: 'approve',
		outputs: [{ name: '', type: 'bool' }],
		type: 'function',
	},
	{
		constant: true,
		inputs: [
			{ name: 'owner', type: 'address' },
			{ name: 'spender', type: 'address' },
		],
		name: 'allowance',
		outputs: [{ name: '', type: 'uint256' }],
		type: 'function',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, name: 'from', type: 'address' },
			{ indexed: true, name: 'to', type: 'address' },
			{ indexed: false, name: 'amount', type: 'uint256' },
		],
		name: 'Transfer',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, name: 'owner', type: 'address' },
			{ indexed: true, name: 'spender', type: 'address' },
			{ indexed: false, name: 'amount', type: 'uint256' },
		],
		name: 'Approval',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, name: 'cashPrior', type: 'uint256' },
			{ indexed: false, name: 'interestAccumulated', type: 'uint256' },
			{ indexed: false, name: 'borrowIndex', type: 'uint256' },
			{ indexed: false, name: 'totalBorrows', type: 'uint256' },
		],
		name: 'AccrueInterest',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, name: 'minter', type: 'address' },
			{ indexed: false, name: 'mintAmount', type: 'uint256' },
			{ indexed: false, name: 'mintTokens', type: 'uint256' },
		],
		name: 'Mint',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, name: 'redeemer', type: 'address' },
			{ indexed: false, name: 'redeemAmount', type: 'uint256' },
			{ indexed: false, name: 'redeemTokens', type: 'uint256' },
		],
		name: 'Redeem',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, name: 'borrower', type: 'address' },
			{ indexed: false, name: 'borrowAmount', type: 'uint256' },
			{ indexed: false, name: 'accountBorrows', type: 'uint256' },
			{ indexed: false, name: 'totalBorrows', type: 'uint256' },
		],
		name: 'Borrow',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, name: 'payer', type: 'address' },
			{ indexed: false, name: 'borrower', type: 'address' },
			{ indexed: false, name: 'repayAmount', type: 'uint256' },
			{ indexed: false, name: 'accountBorrows', type: 'uint256' },
			{ indexed: false, name: 'totalBorrows', type: 'uint256' },
		],
		name: 'RepayBorrow',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, name: 'liquidator', type: 'address' },
			{ indexed: false, name: 'borrower', type: 'address' },
			{ indexed: false, name: 'repayAmount', type: 'uint256' },
			{ indexed: false, name: 'cTokenCollateral', type: 'address' },
			{ indexed: false, name: 'seizeTokens', type: 'uint256' },
		],
		name: 'LiquidateBorrow',
		type: 'event',
	},
]
