/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaoClaim } from '../../typechain/BaoClaim'
export * as factories from './factories'
export { BaoClaim__factory } from '../../typechain/factories/BaoClaim__factory'
